questions:
    label: Question
    manage:
        form: $/alexwenzel/octoberfaqs/models/question/fields.yaml
    view:
        list: $/alexwenzel/octoberfaqs/models/question/columns.yaml
        toolbarButtons: create|delete
        showSorting: false
        defaultSort:
          column: sort_order
          direction: asc
