name: FAQ
form: $/alexwenzel/octoberfaqs/models/faq/fields.yaml
modelClass: Alexwenzel\OctoberFaqs\Models\FAQ

create:
    title: New FAQ
    redirect: alexwenzel/octoberfaqs/faqs/update/:id
    redirectClose: alexwenzel/octoberfaqs/faqs/update/:id

update:
    title: Edit FAQ
    redirect: alexwenzel/octoberfaqs/faqs
    redirectClose: alexwenzel/octoberfaqs/faqs
