# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Reorder Questions

# Attribute name
nameFrom: question

# Model Class name
modelClass: Alexwenzel\OctoberFaqs\Models\Question

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
